### ISSUE TITLE
keeps running forever

### ISSUE THREAD

**Issue by zanona** [agladysh/lua2json#1]
I've just installed on osx lion following the instructions, but:

```
$ lua2json test.lua data.json
```

keeps running forever and does not generate any file.

Any idea?

Thanks :)

**Comment by agladysh** [comment]
`lua2json` works with stdin and stdout. Use `$ lua2json <test.lua >data.json`

**Comment by zanona** [comment]
Sorry, now I'm getting another error:

[test.lua](https://gist.github.com/1160594), 

```
$ lua2json <test.lua >data.json
lua: (command line):37: bad argument #1 to 'assert' (value expected)
stack traceback:
    [C]: in function 'assert'
    (command line):37: in main chunk
    [C]: ?
```

Not sure, but perhaps it might be something with the document?
it is an auto generated document from [Tiled](http://www.mapeditor.org/)

Thanks

**Comment by agladysh** [comment]
Use `lua2json -r <test.lua >data.json`. The lua2json expects by default that the data is prefixed with `return`. The `-r` option makes it add the prefix explicitly.

I will improve the error message in the next version.

**Comment by agladysh** [comment]
Done in v0.1.1
